[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.128.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture --buildDrafts"

[context.branch-deploy]
  command = "hugo --gc --minify --buildFuture"
